### ISSUE TITLE
Ehm, does it even work?

### ISSUE THREAD

**Issue by mudrd8mz** [danielneis/moodle-mod_paypal#10]
OK, so I think this module has really good idea and potential. I see many benefits when compared to the enrol_paypal solution. The main one is that you can open the course for free but have just some examples available by default. The main contents of the course would unlock only after received payment. That's the main use case imho (am I right?).

But then I found the `paypal_get_completion_state()` and realized this is not even finished. So the activity actually always appears as completed. What is the whole point then?

**Comment by danielneis** [comment]
Hello,

sorry for the buggy submission.
I've fixed this, adding the same test that is made on the view screen:
if there is a transaction for that user on that module, it is showed as completed.
it also must test the status of the transaction to see if it is really completed or had errors. will do it soon.

thank you very much for the review!

Kind regards,
Daniel

**Comment by danielneis** [comment]
last commits fixed the completeness queries =)
