### ISSUE TITLE
Can you use just required_param() instead of parsing the $_POST manually in ipn.php?

### ISSUE THREAD

**Issue by mudrd8mz** [danielneis/moodle-mod_paypal#8]

**Comment by danielneis** [comment]
Hello,

this code was copied from enrol/paypal/ipn.php and backs to 2004,
you can take a look at the history using 

```
git log  -L59,62:enrol/paypal/ipn.php
```

Should I fix it there too?

Kind regards,
Daniel

**Comment by mudrd8mz** [comment]
Yeah, I am aware of it. It is again one of those cases when even core/standard code is not the best example to follow. You are indeed warmly welcome to open an issue in the tracker and propose a fix for enrol_paypal. Thanks in advance.

**Comment by danielneis** [comment]
For what i've understood, params should be optional because there is a redirect step in the process.
It is registering "pending" transactions now. Should be working for "Completed" too.
I've tested via sandbox, may have to accept payments yet ...
